#!/bin/sh

echo ""
echo "======================================================================"
echo ""
echo "Welcome to jupyter-book-tools!"
echo ""
echo "Use the genbook command to convert any notebook files to PDF e.g."
echo ""
echo "   $ genbook chapter1.ipynb"
echo ""
echo "The program uses a custom template /etc/booktemplate.tplx by default."
echo "To customize, make a copy of the file and pass it as an argument to"
echo "genbook command."
echo ""
echo "Any questions?  Please submit an issue at the github repo."
echo "https://github.com/tk3369/jupyter-book-tools/"
echo ""
echo "======================================================================"
echo ""

exec /bin/bash
